[package]
name = "ffff"
version = "1.0.0"
edition = "2021"
authors = ["Alfarel Sandriano"]
description = "An esolang inspired by absolutely no one important."

[dependencies]
thiserror = "2.0.9"
clap = { version = "4.5.23", features = ["derive"] }